#!/usr/bin/env node
/**
 * PreCompact Hook - Saves session state before context compaction
 *
 * This hook fires before Claude Code compacts the conversation.
 * It captures key context that might be lost during compaction.
 */

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = process.cwd();
const STATE_FILE = path.join(PROJECT_ROOT, '.claude', 'CONTEXT_SNAPSHOT.md');
const SESSION_NOTES = path.join(PROJECT_ROOT, 'SESSION_NOTES.md');

function getTimestamp() {
  return new Date().toISOString().replace('T', ' ').split('.')[0];
}

function readFileIfExists(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    return null;
  }
}

function extractRecentTodos() {
  // Read from stdin if available (hook receives context)
  let input = '';
  try {
    input = fs.readFileSync(0, 'utf8');
  } catch {
    // No stdin available
  }

  // Try to extract TODO items from the input
  const todoMatch = input.match(/## Current Tasks[\s\S]*?(?=##|$)/i);
  return todoMatch ? todoMatch[0].trim() : null;
}

function main() {
  const timestamp = getTimestamp();

  // Read existing session notes for context
  const sessionNotes = readFileIfExists(SESSION_NOTES);

  // Build snapshot content
  let snapshot = `# Context Snapshot

**Captured:** ${timestamp}
**Trigger:** PreCompact (auto-compaction imminent)

## Purpose

This snapshot was automatically captured before context compaction.
Review this file to recover context that may have been summarized.

`;

  // Include current working state if session notes exist
  if (sessionNotes) {
    // Extract just the recent/active sections
    const recentWork = sessionNotes.match(/## Recent Work[\s\S]*?(?=## |$)/i);
    const currentFocus = sessionNotes.match(/## Current Focus[\s\S]*?(?=## |$)/i);
    const activeIssues = sessionNotes.match(/## Active Issues[\s\S]*?(?=## |$)/i);

    if (currentFocus) {
      snapshot += currentFocus[0] + '\n\n';
    }
    if (recentWork) {
      snapshot += recentWork[0] + '\n\n';
    }
    if (activeIssues) {
      snapshot += activeIssues[0] + '\n\n';
    }
  }

  // Add recovery instructions
  snapshot += `## Recovery Instructions

If you're reading this after a compaction event:
1. Review SESSION_NOTES.md for full context
2. Check git log for recent commits
3. Review any TODO comments in recently modified files

---
*Auto-generated by pre-compact hook*
`;

  // Write snapshot
  fs.writeFileSync(STATE_FILE, snapshot);

  // Log to stderr (stdout goes back to Claude)
  console.error(`[pre-compact] Snapshot saved to ${STATE_FILE}`);
}

main();
