#!/usr/bin/env node
/**
 * Stop Hook - Captures final session state when Claude stops
 *
 * This hook fires when Claude Code stops (user interrupts or task completes).
 * It saves the final state for the next session to pick up.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PROJECT_ROOT = process.cwd();
const SESSION_LOG = path.join(PROJECT_ROOT, '.claude', 'session-log.jsonl');
const STATE_FILE = path.join(PROJECT_ROOT, '.claude', 'LAST_SESSION.md');

function getTimestamp() {
  return new Date().toISOString();
}

function getRecentCommits(count = 3) {
  try {
    return execSync(`git log --oneline -${count}`, {
      cwd: PROJECT_ROOT,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe']
    }).trim();
  } catch {
    return null;
  }
}

function getModifiedFiles() {
  try {
    // Files modified in the last hour
    return execSync('git diff --name-only HEAD~5 2>/dev/null || git diff --name-only', {
      cwd: PROJECT_ROOT,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe']
    }).trim();
  } catch {
    return null;
  }
}

function appendToLog(entry) {
  try {
    fs.appendFileSync(SESSION_LOG, JSON.stringify(entry) + '\n');
  } catch (err) {
    console.error(`[session-stop] Failed to write log: ${err.message}`);
  }
}

function main() {
  const timestamp = getTimestamp();
  const stopReason = process.env.CLAUDE_STOP_REASON || 'unknown';

  // Log session end
  const logEntry = {
    event: 'session_stop',
    timestamp,
    reason: stopReason,
    cwd: PROJECT_ROOT
  };

  // Get recent work context
  const commits = getRecentCommits();
  const modifiedFiles = getModifiedFiles();

  if (commits) {
    logEntry.recent_commits = commits.split('\n');
  }
  if (modifiedFiles) {
    logEntry.modified_files = modifiedFiles.split('\n').filter(f => f);
  }

  appendToLog(logEntry);

  // Write human-readable state file
  let state = `# Last Session Summary

**Ended:** ${timestamp.replace('T', ' ').split('.')[0]}
**Reason:** ${stopReason}

`;

  if (commits) {
    state += `## Recent Commits

\`\`\`
${commits}
\`\`\`

`;
  }

  if (modifiedFiles) {
    const files = modifiedFiles.split('\n').filter(f => f);
    if (files.length > 0) {
      state += `## Files Modified This Session

${files.map(f => `- ${f}`).join('\n')}

`;
    }
  }

  state += `## Next Session

Review SESSION_NOTES.md for context on what to continue working on.

---
*Auto-generated by session-stop hook*
`;

  fs.writeFileSync(STATE_FILE, state);

  console.error(`[session-stop] Session state saved`);
}

main();
